// Simple translation system following SubHub's established patterns
export type SupportedLanguage = 'en' | 'it';

// Simple translation object - no over-engineering
export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    subscriptions: 'Subscriptions',
    reports: 'Reports',
    categories: 'Categories',
    settings: 'Settings',
    help: 'Help',
    
    // Common buttons
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    
    // Subscription terms
    cost: 'Cost',
    frequency: 'Frequency',
    monthly: 'Monthly',
    yearly: 'Yearly',
    nextBilling: 'Next Billing',
    
    // Messages
    loading: 'Loading...',
    noData: 'No data available',
    comingSoon: 'Coming Soon',
    
    // Settings
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    budget: 'Budget',

    // Budget Management
    budgetConfiguration: 'Budget Configuration',
    monthlyBudget: 'Monthly Budget',
    yearlyBudget: 'Yearly Budget',
    categoryBudgets: 'Category Budgets',
    budgetAlerts: 'Budget Alerts',
    budgetOverview: 'Budget Overview',
    currentSpending: 'Current Spending',
    remainingBudget: 'Remaining Budget',
    budgetProgress: 'Budget Progress',
    setBudget: 'Set Budget',
    addCategory: 'Add Category',
    removeCategory: 'Remove Category',
    budgetSettingsSaved: 'Budget settings saved successfully',
    budgetReset: 'Budget settings reset to defaults',
    confirmResetBudget: 'Are you sure you want to reset all budget settings?',
    enableBudgetAlerts: 'Enable budget alerts',
    budgetAlertDescription: 'Receive notifications when approaching budget limits',
    clear: 'Clear',
    clearBudget: 'Clear budget',
    monthlyBudgetDescription: 'Set your monthly subscription spending limit',
    yearlyBudgetDescription: 'Set your annual subscription spending limit',
    budgetHelpText: 'Leave empty to disable budget tracking',
    budgetSuggestions: 'Suggested budgets',
    useMonthlyBudget: 'Use monthly × 12',
    monthlyEquivalent: 'Monthly equivalent',
    yearlyBudgetHelpText: 'Leave empty to disable yearly budget tracking',
    basedOnMonthly: 'Based on monthly',
    categoryBudgetDescription: 'Set spending limits for specific categories',
    categoryName: 'Category name',
    budgetExceeded: 'Budget exceeded',
    approachingLimit: 'Approaching budget limit',
    noCategoryBudgets: 'No category budgets set',
    addCategoryToStart: 'Add a category to get started',
    alertAt50: 'Alert when 50% of budget is used',
    alertAt75: 'Alert when 75% of budget is used',
    alertAt90: 'Alert when 90% of budget is used',
    alertAt100: 'Alert when budget is exceeded',
    monthlyBudgetAlerts: 'Monthly budget alerts',
    monthlyBudgetAlertsDesc: 'Get notified about monthly budget status',
    yearlyBudgetAlerts: 'Yearly budget alerts',
    yearlyBudgetAlertsDesc: 'Get notified about yearly budget status',
    categoryBudgetAlerts: 'Category budget alerts',
    categoryBudgetAlertsDesc: 'Get notified about category-specific budget limits',
    alertTypes: 'Alert Types',
    alertThresholds: 'Alert Thresholds',
    hideAdvanced: 'Hide Advanced',
    showAdvanced: 'Show Advanced',
    defaultThreshold: 'Default threshold',
    recommended: 'Recommended',
    notificationMethods: 'Notification Methods',
    inAppNotifications: 'In-app notifications',
    inAppNotificationsDesc: 'Show alerts within the application',
    emailNotifications: 'Email notifications',
    emailNotificationsDesc: 'Send alerts to your email address',
    alertPreview: 'Alert Preview',
    alertPreviewText: 'You\'ve used 75% of your monthly Entertainment budget ($75 of $100)',
    budgetAlertsDisabled: 'Budget alerts are disabled',
    enableAlertsToReceive: 'Enable alerts to receive notifications about your budget status',
    budgetLimit: 'Budget limit',
    noMonthlyBudget: 'No monthly budget set',
    noYearlyBudget: 'No yearly budget set',
    currentMonthlySpending: 'Current spending',
    currentYearlySpending: 'Current spending',
    monthlyStatus: 'Monthly',
    yearlyStatus: 'Yearly',
    onTrack: 'On Track',
    warning: 'Warning',
    exceeded: 'Exceeded',
    saving: 'Saving...',
    resetBudget: 'Reset Budget',
    unsavedChanges: 'You have unsaved changes',
    allChangesSaved: 'All changes saved',
    editBudget: 'Edit Budget',
    noBudgetSet: 'No budget set',
    setBudgetToTrack: 'Set a budget to track your subscription spending',
    currentTotalSpending: 'Current monthly spending',
    overallBudgetStatus: 'Overall budget status',
    thisMonth: 'This month',
    monthlySpending: 'Monthly spending',
    yearlySpending: 'Yearly spending',
    spent: 'Spent',
    remaining: 'Remaining',
    over: 'Over',
    topCategories: 'Top categories',
    adjustBudget: 'Adjust Budget',
    viewInsights: 'View Insights',
    budgetExceededBy: 'Budget exceeded by',
    approachingBudgetLimit: 'Approaching budget limit',
    viewAll: 'View All',
    subscriptionsCount: 'subscriptions',
    noBudget: 'No budget',
    setCategoryBudgetsToTrack: 'Set category budgets to track spending by category',
    month: 'mo',
    year: 'yr',
    categoriesWithBudgets: 'With budgets',
    overBudget: 'Over budget',
    considerYearlyBudget: 'Consider setting a yearly budget',
    yearlyBudgetInsight: 'You have more yearly subscriptions than monthly ones. A yearly budget could help track annual spending.',
    spendingConcentrated: 'Spending concentrated in one category',
    spendingConcentrationInsight: 'accounts for a large portion of your spending. Consider diversifying or setting category limits.',
    setCategoryBudgets: 'Set Category Budgets',
    reviewOldSubscriptions: 'Review long-running subscriptions',
    oldSubscriptionsInsight: 'subscriptions older than 6 months. Consider reviewing their usage.',
    reviewSubscriptions: 'Review Subscriptions',
    budgetOptimization: 'Budget optimization opportunity',
    budgetOptimizationInsight: 'less than your budget. Consider reallocating or saving this amount.',
    budgetWarning: 'Budget Warning',
    budgetHealthy: 'Budget Healthy',
    budgetInsight: 'Budget Insight',
    budgetInsights: 'Budget Insights',
    insights: 'insights',
    noInsightsAvailable: 'No insights available',
    insightsWillAppear: 'Insights will appear as you use budget features and add subscriptions',
    dismissInsight: 'Dismiss insight',
    viewMoreInsights: 'View more insights',
    totalSpending: 'Total spending',
    activeAlerts: 'Active alerts',
    overallStatus: 'Overall status',
    healthy: 'Healthy',
    noActiveAlerts: 'No active alerts',
    budgetAlertsAllClear: 'Your budget is on track',
    clearAll: 'Clear All',
    critical: 'Critical',
    actionRequired: 'Action Required',
    reviewBudgetOrSpending: 'Review your budget or spending',
    acknowledgeAlert: 'Acknowledge alert',
    showLess: 'Show Less',
    showMore: 'Show More',
    criticalAlerts: 'critical alerts',
    immediateAttentionRequired: 'Immediate attention required',
    spendingTrend: 'Spending Trend',
    lastPeriod: 'Last period',
    overall: 'Overall',
    average: 'Average',
    avgVariance: 'Avg variance',
    last6Periods: 'Last 6 periods',
    spendingIncreasing: 'Your spending is increasing',
    overPeriod: 'over period',
    spendingDecreasing: 'Your spending is decreasing',
    reduction: 'reduction',
    averageBudgetVariance: 'Average budget variance',
    noOptimizationData: 'No optimization data',
    addSubscriptionsForOptimization: 'Add subscriptions to get optimization recommendations',
    budgetOptimizationTitle: 'Budget Optimization',
    score: 'Score',
    potentialSavings: 'Potential savings',
    highPriorityActions: 'High priority',
    quickWins: 'Quick wins',
    efficiency: 'Efficiency',
    allRecommendations: 'All',
    longTerm: 'Long-term',
    noRecommendationsInCategory: 'No recommendations in this category',
    easy: 'Easy',
    moderate: 'Moderate',
    difficult: 'Difficult',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    impact: 'Impact',
    takeAction: 'Take Action',
    categoriesNeedingAttention: 'Categories needing attention',
    updateAvailable: 'Update Available',
    updateAvailableDescription: 'A new version of SubHub is available. Reload to update.',
    reload: 'Reload',
    later: 'Later',
    close: 'Close',
    offlineReady: 'Offline Ready',
    offlineReadyDescription: 'SubHub is now available offline. You can view your subscriptions without an internet connection.',
    subscriptionManager: 'Subscription Manager',
    installApp: 'Install SubHub',
    installAppDescription: 'Get quick access to your subscriptions. Install SubHub on your device for a better experience.',
    offlineAccess: 'Works offline',
    fastLoading: 'Fast loading',
    homeScreenAccess: 'Home screen access',
    install: 'Install',
    notNow: 'Not now',
    offlineMode: 'Offline Mode',
    viewingCachedData: 'Viewing cached data from',
    noCachedData: 'No cached data available',
    cachedSubscriptions: 'subscriptions cached',
    backOnline: 'Back Online',
    dataWillUpdate: 'Your data will update automatically',
    dataAvailableOffline: 'subscriptions available offline',

    // Notification Preferences
    notificationPreferences: 'Notification Preferences',
    renewalReminders: 'Renewal Reminders',
    enableRenewalReminders: 'Enable renewal reminders',
    renewalRemindersDescription: 'Get notified before your subscriptions renew',
    reminderDays: 'Remind me',
    '1Day': '1 day before',
    nDays: '{n} days before',
    spendingAlerts: 'Spending Alerts',
    enableSpendingAlerts: 'Enable spending alerts',
    spendingAlertsDescription: 'Get notified when approaching budget limits',
    alertThreshold: 'Alert threshold',
    unusedSubscriptions: 'Unused Subscriptions',
    enableUnusedDetection: 'Enable unused detection',
    unusedDetectionDescription: 'Get notified about subscriptions you haven\'t used',
    inactiveDays: 'Consider inactive after',
    days: 'days',
    deliveryPreferences: 'Delivery Preferences',
    emailNotificationsPref: 'Email notifications',
    emailNotificationsPrefDescription: 'Receive alerts via email',
    pushNotificationsPref: 'Push notifications',
    pushNotificationsPrefDescription: 'Receive browser notifications',
    inAppNotificationsPref: 'In-app notifications',
    inAppNotificationsPrefDescription: 'Show notifications within the app',
    quietHours: 'Quiet Hours',
    enableQuietHours: 'Enable quiet hours',
    quietHoursDescription: 'Pause notifications during specified hours',
    startTime: 'Start time',
    endTime: 'End time',
    advancedSettings: 'Advanced Settings',
    maxDailyNotifications: 'Maximum daily notifications',
    maxDailyNotificationsDescription: 'Limit the number of notifications per day',
    unlimited: 'Unlimited',

    // Renewal Reminders
    upcomingRenewals: 'Upcoming Renewals',
    checkReminders: 'Check Reminders',
    totalUpcoming: 'Total upcoming',
    urgentRenewals: 'Urgent',
    noUpcomingRenewals: 'No upcoming renewals',
    noUpcomingRenewalsDescription: 'All your subscriptions are up to date',
    tomorrow: 'Tomorrow',
    inNDays: 'In {n} days',
    inNWeeks: 'In {n} week(s)',
    andNMore: 'and {n} more',
    viewAllRenewals: 'View All',
    manageSubscriptions: 'Manage',

    // Spending Alerts
    spendingAlertsTitle: 'Spending Alerts',
    checkAlerts: 'Check Alerts',
    budgetUsed: 'Budget used',
    activeAlertsCount: 'Active alerts',
    overallBudget: 'Overall budget',
    noSpendingAlerts: 'No spending alerts',
    budgetOnTrack: 'Your budget is on track',
    budgetLabel: 'budget',
    usedLabel: 'used',
    exceededStatus: 'Exceeded',
    warningStatus: 'Warning',
    adjustBudgets: 'Adjust Budgets',
    viewDetailsButton: 'View Details',

    // Dashboard UX Optimization
    monthlyBudgetStatus: 'Monthly Budget Status',
    monthlyLabel: 'Monthly',
    yearlyLabel: 'Yearly',
    subscriptionsLabel: 'Subscriptions',
    renewalsDueSoon: 'Due Soon',
    criticalAlertsTitle: 'Critical Alerts',
    allGoodStatus: 'All Good!',
    noActiveAlertsMessage: 'No active alerts at this time',
    viewAllButton: 'View All',
    andNMoreAlertsText: 'and {n} more alerts',
    viewMoreButton: 'View More',
    showLessButton: 'Show Less',

    // Unused Subscriptions
    unusedSubscriptionsTitle: 'Unused Subscriptions',
    checkUnused: 'Check Unused',
    usageEfficiencyLabel: 'Usage efficiency',
    potentialSavingsLabel: 'Potential savings',
    allSubscriptionsActive: 'All subscriptions active',
    noUnusedSubscriptionsFound: 'No unused subscriptions found',
    inactiveFor: 'Inactive for',
    nDaysLabel: '{n} days',
    nWeeksLabel: '{n} weeks',
    nMonthsLabel: '{n} months',
    nYearsLabel: '{n} years',
    couldSave: 'Could save',
    criticalStatusLabel: 'Critical',
    warningStatusLabel: 'Warning',
    andNMoreUnused: 'and {n} more unused',
    reviewSubscriptionsButton: 'Review Subscriptions',
    adjustSettingsButton: 'Adjust Settings',
    usageInsightLabel: 'Usage Insight',
    criticalUnusedInsight: 'You have {count} critically unused subscriptions. Consider canceling them to save {savings}/month.',
    warningUnusedInsight: 'You have {count} potentially unused subscriptions. Review them to save {savings}/month.',

    // Smart Scheduling
    smartSchedulingTitle: 'Smart Scheduling',
    smartSchedulingEnabled: 'Smart scheduling active',
    smartSchedulingDisabled: 'Smart scheduling disabled',
    processing: 'Processing...',
    processNow: 'Process Now',
    nextOptimalTime: 'Next optimal time',
    efficiencyScore: 'Efficiency score',
    excellent: 'Excellent',
    good: 'Good',
    needsImprovement: 'Needs improvement',
    lastProcessingResults: 'Last processing results',
    immediate: 'Immediate',
    batched: 'Batched',
    deferred: 'Deferred',
    lastProcessed: 'Last processed',
    deliveryEfficiency: 'Delivery Efficiency',
    immediateDelivery: 'Immediate delivery',
    batchedDelivery: 'Batched delivery',
    deferredDelivery: 'Deferred delivery',
    quietHoursActive: 'Quiet hours active',
    notificationsPaused: 'Notifications are paused during quiet hours',
    enableInSettings: 'Enable smart scheduling in settings for optimal notification delivery',
    goToSettings: 'Go to Settings',
    now: 'now',
    inNMinutesShort: 'in {n} minutes',
    inNHoursShort: 'in {n} hours',
    inNDaysShort: 'in {n} days',
    unknown: 'unknown',

    // Additional UI
    profile: 'Profile',
    notifications: 'Notifications',
    appearance: 'Appearance',
    privacy: 'Privacy',
    logout: 'Logout',
    welcome: 'Welcome',

    // Landing page
    features: 'Features',
    pricing: 'Pricing',
    testimonials: 'Testimonials',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    heroTag: 'Save $200-400 per year on unused subscriptions',
    heroTitle1: 'Take Control of Your',
    heroTitle2: 'Subscriptions',
    heroSubtitle: 'Stop wasting money on forgotten subscriptions. SubHub helps you track, manage, and optimize all your recurring payments with intelligent insights.',
    startFree: 'Start Free Today',
    watchDemo: 'Watch Demo',
    freeForever: 'Free forever',
    noCredit: 'No credit card required',
    setup: '2-minute setup',
    valueTitle: 'Why SubHub Users Save Money',
    valueSubtitle: 'Our intelligent system helps you identify and eliminate subscription waste automatically',
    avgSavings: 'Average Annual Savings',
    avgSavingsDesc: 'From cancelled unused subscriptions',
    usersReduce: 'Users Reduce Spending',
    usersReduceDesc: 'Within first 30 days',
    avgUnused: 'Unused Subscriptions',
    avgUnusedDesc: 'Found per user on average',
    featuresTitle: 'Everything You Need to Manage Subscriptions',
    featuresSubtitle: 'Powerful features designed to help you save money and stay organized',
    smartTracking: 'Smart Tracking',
    smartTrackingDesc: 'Automatically categorize and track all your subscriptions with intelligent spending insights',
    smartReminders: 'Smart Reminders',
    smartRemindersDesc: 'Never miss a renewal with intelligent notifications that respect your schedule',
    unusedDetection: 'Unused Detection',
    unusedDetectionDesc: 'AI-powered analysis identifies subscriptions you\'re not using to maximize savings',
    budgetManagement: 'Budget Management',
    budgetManagementDesc: 'Set spending limits and get alerts when approaching your budget thresholds',
    renewalCalendar: 'Renewal Calendar',
    renewalCalendarDesc: 'Visual calendar view of all upcoming renewals and payment dates',
    mobileFirst: 'Mobile First',
    mobileFirstDesc: 'Responsive design that works perfectly on all devices with PWA support'
  },
  it: {
    // Navigation
    dashboard: 'Dashboard',
    subscriptions: 'Abbonamenti',
    reports: 'Report',
    categories: 'Categorie',
    settings: 'Impostazioni',
    help: 'Aiuto',
    
    // Common buttons
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    edit: 'Modifica',
    add: 'Aggiungi',
    search: 'Cerca',
    
    // Subscription terms
    cost: 'Costo',
    frequency: 'Frequenza',
    monthly: 'Mensile',
    yearly: 'Annuale',
    nextBilling: 'Prossima Fatturazione',
    
    // Messages
    loading: 'Caricamento...',
    noData: 'Nessun dato disponibile',
    comingSoon: 'Prossimamente',
    
    // Settings
    language: 'Lingua',
    currency: 'Valuta',
    theme: 'Tema',
    budget: 'Budget',

    // Budget Management
    budgetConfiguration: 'Configurazione Budget',
    monthlyBudget: 'Budget Mensile',
    yearlyBudget: 'Budget Annuale',
    categoryBudgets: 'Budget per Categoria',
    budgetAlerts: 'Avvisi Budget',
    budgetOverview: 'Panoramica Budget',
    currentSpending: 'Spesa Attuale',
    remainingBudget: 'Budget Rimanente',
    budgetProgress: 'Progresso Budget',
    setBudget: 'Imposta Budget',
    addCategory: 'Aggiungi Categoria',
    removeCategory: 'Rimuovi Categoria',
    budgetSettingsSaved: 'Impostazioni budget salvate con successo',
    budgetReset: 'Impostazioni budget ripristinate ai valori predefiniti',
    confirmResetBudget: 'Sei sicuro di voler ripristinare tutte le impostazioni del budget?',
    enableBudgetAlerts: 'Abilita avvisi budget',
    budgetAlertDescription: 'Ricevi notifiche quando ti avvicini ai limiti del budget',
    clear: 'Cancella',
    clearBudget: 'Cancella budget',
    monthlyBudgetDescription: 'Imposta il limite di spesa mensile per gli abbonamenti',
    yearlyBudgetDescription: 'Imposta il limite di spesa annuale per gli abbonamenti',
    budgetHelpText: 'Lascia vuoto per disabilitare il monitoraggio del budget',
    budgetSuggestions: 'Budget suggeriti',
    useMonthlyBudget: 'Usa mensile × 12',
    monthlyEquivalent: 'Equivalente mensile',
    yearlyBudgetHelpText: 'Lascia vuoto per disabilitare il monitoraggio del budget annuale',
    basedOnMonthly: 'Basato sul mensile',
    categoryBudgetDescription: 'Imposta limiti di spesa per categorie specifiche',
    categoryName: 'Nome categoria',
    budgetExceeded: 'Budget superato',
    approachingLimit: 'Avvicinandosi al limite del budget',
    noCategoryBudgets: 'Nessun budget per categoria impostato',
    addCategoryToStart: 'Aggiungi una categoria per iniziare',
    alertAt50: 'Avvisa quando viene utilizzato il 50% del budget',
    alertAt75: 'Avvisa quando viene utilizzato il 75% del budget',
    alertAt90: 'Avvisa quando viene utilizzato il 90% del budget',
    alertAt100: 'Avvisa quando il budget viene superato',
    monthlyBudgetAlerts: 'Avvisi budget mensile',
    monthlyBudgetAlertsDesc: 'Ricevi notifiche sullo stato del budget mensile',
    yearlyBudgetAlerts: 'Avvisi budget annuale',
    yearlyBudgetAlertsDesc: 'Ricevi notifiche sullo stato del budget annuale',
    categoryBudgetAlerts: 'Avvisi budget categoria',
    categoryBudgetAlertsDesc: 'Ricevi notifiche sui limiti di budget specifici per categoria',
    alertTypes: 'Tipi di Avviso',
    alertThresholds: 'Soglie di Avviso',
    hideAdvanced: 'Nascondi Avanzate',
    showAdvanced: 'Mostra Avanzate',
    defaultThreshold: 'Soglia predefinita',
    recommended: 'Raccomandato',
    notificationMethods: 'Metodi di Notifica',
    inAppNotifications: 'Notifiche in-app',
    inAppNotificationsDesc: 'Mostra avvisi all\'interno dell\'applicazione',
    emailNotifications: 'Notifiche email',
    emailNotificationsDesc: 'Invia avvisi al tuo indirizzo email',
    alertPreview: 'Anteprima Avviso',
    alertPreviewText: 'Hai utilizzato il 75% del tuo budget mensile Intrattenimento (€75 di €100)',
    budgetAlertsDisabled: 'Gli avvisi budget sono disabilitati',
    enableAlertsToReceive: 'Abilita gli avvisi per ricevere notifiche sullo stato del tuo budget',
    budgetLimit: 'Limite budget',
    noMonthlyBudget: 'Nessun budget mensile impostato',
    noYearlyBudget: 'Nessun budget annuale impostato',
    currentMonthlySpending: 'Spesa attuale',
    currentYearlySpending: 'Spesa attuale',
    monthlyStatus: 'Mensile',
    yearlyStatus: 'Annuale',
    onTrack: 'In Linea',
    warning: 'Attenzione',
    exceeded: 'Superato',
    saving: 'Salvando...',
    resetBudget: 'Ripristina Budget',
    unsavedChanges: 'Hai modifiche non salvate',
    allChangesSaved: 'Tutte le modifiche salvate',
    editBudget: 'Modifica Budget',
    noBudgetSet: 'Nessun budget impostato',
    setBudgetToTrack: 'Imposta un budget per monitorare la spesa degli abbonamenti',
    currentTotalSpending: 'Spesa mensile attuale',
    overallBudgetStatus: 'Stato generale del budget',
    thisMonth: 'Questo mese',
    monthlySpending: 'Spesa mensile',
    yearlySpending: 'Spesa annuale',
    spent: 'Speso',
    remaining: 'Rimanente',
    over: 'Oltre',
    topCategories: 'Categorie principali',
    adjustBudget: 'Regola Budget',
    viewInsights: 'Visualizza Approfondimenti',
    budgetExceededBy: 'Budget superato di',
    approachingBudgetLimit: 'Avvicinandosi al limite del budget',
    viewAll: 'Visualizza Tutto',
    subscriptionsCount: 'abbonamenti',
    noBudget: 'Nessun budget',
    setCategoryBudgetsToTrack: 'Imposta budget per categoria per monitorare la spesa per categoria',
    month: 'mese',
    year: 'anno',
    categoriesWithBudgets: 'Con budget',
    overBudget: 'Oltre il budget',
    considerYearlyBudget: 'Considera di impostare un budget annuale',
    yearlyBudgetInsight: 'Hai più abbonamenti annuali che mensili. Un budget annuale potrebbe aiutare a monitorare la spesa annuale.',
    spendingConcentrated: 'Spesa concentrata in una categoria',
    spendingConcentrationInsight: 'rappresenta una grande parte della tua spesa. Considera di diversificare o impostare limiti per categoria.',
    setCategoryBudgets: 'Imposta Budget per Categoria',
    reviewOldSubscriptions: 'Rivedi abbonamenti di lunga durata',
    oldSubscriptionsInsight: 'abbonamenti più vecchi di 6 mesi. Considera di rivedere il loro utilizzo.',
    reviewSubscriptions: 'Rivedi Abbonamenti',
    budgetOptimization: 'Opportunità di ottimizzazione del budget',
    budgetOptimizationInsight: 'meno del tuo budget. Considera di riallocare o risparmiare questo importo.',
    budgetWarning: 'Avviso Budget',
    budgetHealthy: 'Budget Sano',
    budgetInsight: 'Approfondimento Budget',
    budgetInsights: 'Approfondimenti Budget',
    insights: 'approfondimenti',
    noInsightsAvailable: 'Nessun approfondimento disponibile',
    insightsWillAppear: 'Gli approfondimenti appariranno mentre usi le funzionalità del budget e aggiungi abbonamenti',
    dismissInsight: 'Ignora approfondimento',
    viewMoreInsights: 'Visualizza più approfondimenti',
    totalSpending: 'Spesa totale',
    activeAlerts: 'Avvisi attivi',
    overallStatus: 'Stato generale',
    healthy: 'Sano',
    noActiveAlerts: 'Nessun avviso attivo',
    budgetAlertsAllClear: 'Il tuo budget è in linea',
    clearAll: 'Cancella Tutto',
    critical: 'Critico',
    actionRequired: 'Azione Richiesta',
    reviewBudgetOrSpending: 'Rivedi il tuo budget o la spesa',
    acknowledgeAlert: 'Riconosci avviso',
    showLess: 'Mostra Meno',
    showMore: 'Mostra Di Più',
    criticalAlerts: 'avvisi critici',
    immediateAttentionRequired: 'Attenzione immediata richiesta',
    spendingTrend: 'Tendenza di Spesa',
    lastPeriod: 'Ultimo periodo',
    overall: 'Complessivo',
    average: 'Media',
    avgVariance: 'Varianza media',
    last6Periods: 'Ultimi 6 periodi',
    spendingIncreasing: 'La tua spesa sta aumentando',
    overPeriod: 'nel periodo',
    spendingDecreasing: 'La tua spesa sta diminuendo',
    reduction: 'riduzione',
    averageBudgetVariance: 'Varianza media del budget',
    noOptimizationData: 'Nessun dato di ottimizzazione',
    addSubscriptionsForOptimization: 'Aggiungi abbonamenti per ottenere raccomandazioni di ottimizzazione',
    budgetOptimizationTitle: 'Ottimizzazione Budget',
    score: 'Punteggio',
    potentialSavings: 'Risparmi potenziali',
    highPriorityActions: 'Alta priorità',
    quickWins: 'Vittorie rapide',
    efficiency: 'Efficienza',
    allRecommendations: 'Tutte',
    longTerm: 'Lungo termine',
    noRecommendationsInCategory: 'Nessuna raccomandazione in questa categoria',
    easy: 'Facile',
    moderate: 'Moderato',
    difficult: 'Difficile',
    high: 'Alto',
    medium: 'Medio',
    low: 'Basso',
    impact: 'Impatto',
    takeAction: 'Agisci',
    categoriesNeedingAttention: 'Categorie che necessitano attenzione',
    updateAvailable: 'Aggiornamento Disponibile',
    updateAvailableDescription: 'È disponibile una nuova versione di SubHub. Ricarica per aggiornare.',
    reload: 'Ricarica',
    later: 'Più tardi',
    close: 'Chiudi',
    offlineReady: 'Pronto Offline',
    offlineReadyDescription: 'SubHub è ora disponibile offline. Puoi visualizzare i tuoi abbonamenti senza connessione internet.',
    subscriptionManager: 'Gestore Abbonamenti',
    installApp: 'Installa SubHub',
    installAppDescription: 'Accedi rapidamente ai tuoi abbonamenti. Installa SubHub sul tuo dispositivo per una migliore esperienza.',
    offlineAccess: 'Funziona offline',
    fastLoading: 'Caricamento veloce',
    homeScreenAccess: 'Accesso dalla schermata home',
    install: 'Installa',
    notNow: 'Non ora',
    offlineMode: 'Modalità Offline',
    viewingCachedData: 'Visualizzazione dati memorizzati da',
    noCachedData: 'Nessun dato memorizzato disponibile',
    cachedSubscriptions: 'abbonamenti memorizzati',
    backOnline: 'Connesso di Nuovo',
    dataWillUpdate: 'I tuoi dati si aggiorneranno automaticamente',
    dataAvailableOffline: 'abbonamenti disponibili offline',

    // Notification Preferences
    notificationPreferences: 'Preferenze Notifiche',
    renewalReminders: 'Promemoria Rinnovi',
    enableRenewalReminders: 'Abilita promemoria rinnovi',
    renewalRemindersDescription: 'Ricevi notifiche prima del rinnovo degli abbonamenti',
    reminderDays: 'Ricordami',
    '1Day': '1 giorno prima',
    nDays: '{n} giorni prima',
    spendingAlerts: 'Avvisi di Spesa',
    enableSpendingAlerts: 'Abilita avvisi di spesa',
    spendingAlertsDescription: 'Ricevi notifiche quando ti avvicini ai limiti di budget',
    alertThreshold: 'Soglia di avviso',
    unusedSubscriptions: 'Abbonamenti Inutilizzati',
    enableUnusedDetection: 'Abilita rilevamento inutilizzati',
    unusedDetectionDescription: 'Ricevi notifiche per abbonamenti che non usi',
    inactiveDays: 'Considera inattivo dopo',
    days: 'giorni',
    deliveryPreferences: 'Preferenze di Consegna',
    emailNotificationsPref: 'Notifiche email',
    emailNotificationsPrefDescription: 'Ricevi avvisi via email',
    pushNotificationsPref: 'Notifiche push',
    pushNotificationsPrefDescription: 'Ricevi notifiche del browser',
    inAppNotificationsPref: 'Notifiche in-app',
    inAppNotificationsPrefDescription: 'Mostra notifiche nell\'app',
    quietHours: 'Ore Silenziose',
    enableQuietHours: 'Abilita ore silenziose',
    quietHoursDescription: 'Pausa le notifiche durante le ore specificate',
    startTime: 'Ora di inizio',
    endTime: 'Ora di fine',
    advancedSettings: 'Impostazioni Avanzate',
    maxDailyNotifications: 'Massimo notifiche giornaliere',
    maxDailyNotificationsDescription: 'Limita il numero di notifiche al giorno',
    unlimited: 'Illimitato',

    // Renewal Reminders
    upcomingRenewals: 'Rinnovi Imminenti',
    checkReminders: 'Controlla Promemoria',
    totalUpcoming: 'Totale imminente',
    urgentRenewals: 'Urgenti',
    noUpcomingRenewals: 'Nessun rinnovo imminente',
    noUpcomingRenewalsDescription: 'Tutti i tuoi abbonamenti sono aggiornati',
    tomorrow: 'Domani',
    inNDays: 'Tra {n} giorni',
    inNWeeks: 'Tra {n} settimana/e',
    andNMore: 'e altri {n}',
    viewAllRenewals: 'Vedi Tutti',
    manageSubscriptions: 'Gestisci',

    // Spending Alerts
    spendingAlertsTitle: 'Avvisi di Spesa',
    checkAlerts: 'Controlla Avvisi',
    budgetUsed: 'Budget utilizzato',
    activeAlertsCount: 'Avvisi attivi',
    overallBudget: 'Budget complessivo',
    noSpendingAlerts: 'Nessun avviso di spesa',
    budgetOnTrack: 'Il tuo budget è sotto controllo',
    budgetLabel: 'budget',
    usedLabel: 'utilizzato',
    exceededStatus: 'Superato',
    warningStatus: 'Attenzione',
    adjustBudgets: 'Regola Budget',
    viewDetailsButton: 'Vedi Dettagli',

    // Dashboard UX Optimization
    monthlyBudgetStatus: 'Stato Budget Mensile',
    monthlyLabel: 'Mensile',
    yearlyLabel: 'Annuale',
    subscriptionsLabel: 'Abbonamenti',
    renewalsDueSoon: 'In Scadenza',
    criticalAlertsTitle: 'Avvisi Critici',
    allGoodStatus: 'Tutto Bene!',
    noActiveAlertsMessage: 'Nessun avviso attivo al momento',
    viewAllButton: 'Vedi Tutti',
    andNMoreAlertsText: 'e altri {n} avvisi',
    viewMoreButton: 'Vedi Altro',
    showLessButton: 'Mostra Meno',

    // Unused Subscriptions
    unusedSubscriptionsTitle: 'Abbonamenti Inutilizzati',
    checkUnused: 'Controlla Inutilizzati',
    usageEfficiencyLabel: 'Efficienza utilizzo',
    potentialSavingsLabel: 'Risparmi potenziali',
    allSubscriptionsActive: 'Tutti gli abbonamenti attivi',
    noUnusedSubscriptionsFound: 'Nessun abbonamento inutilizzato trovato',
    inactiveFor: 'Inattivo da',
    nDaysLabel: '{n} giorni',
    nWeeksLabel: '{n} settimane',
    nMonthsLabel: '{n} mesi',
    nYearsLabel: '{n} anni',
    couldSave: 'Potresti risparmiare',
    criticalStatusLabel: 'Critico',
    warningStatusLabel: 'Attenzione',
    andNMoreUnused: 'e altri {n} inutilizzati',
    reviewSubscriptionsButton: 'Rivedi Abbonamenti',
    adjustSettingsButton: 'Regola Impostazioni',
    usageInsightLabel: 'Analisi Utilizzo',
    criticalUnusedInsight: 'Hai {count} abbonamenti criticamente inutilizzati. Considera di cancellarli per risparmiare {savings}/mese.',
    warningUnusedInsight: 'Hai {count} abbonamenti potenzialmente inutilizzati. Rivedili per risparmiare {savings}/mese.',

    // Smart Scheduling
    smartSchedulingTitle: 'Pianificazione Intelligente',
    smartSchedulingEnabled: 'Pianificazione intelligente attiva',
    smartSchedulingDisabled: 'Pianificazione intelligente disabilitata',
    processing: 'Elaborazione...',
    processNow: 'Elabora Ora',
    nextOptimalTime: 'Prossimo orario ottimale',
    efficiencyScore: 'Punteggio efficienza',
    excellent: 'Eccellente',
    good: 'Buono',
    needsImprovement: 'Da migliorare',
    lastProcessingResults: 'Ultimi risultati elaborazione',
    immediate: 'Immediato',
    batched: 'Raggruppato',
    deferred: 'Differito',
    lastProcessed: 'Ultima elaborazione',
    deliveryEfficiency: 'Efficienza Consegna',
    immediateDelivery: 'Consegna immediata',
    batchedDelivery: 'Consegna raggruppata',
    deferredDelivery: 'Consegna differita',
    quietHoursActive: 'Ore silenziose attive',
    notificationsPaused: 'Le notifiche sono sospese durante le ore silenziose',
    enableInSettings: 'Abilita la pianificazione intelligente nelle impostazioni per una consegna ottimale delle notifiche',
    goToSettings: 'Vai alle Impostazioni',
    now: 'ora',
    inNMinutesShort: 'tra {n} minuti',
    inNHoursShort: 'tra {n} ore',
    inNDaysShort: 'tra {n} giorni',
    unknown: 'sconosciuto',

    // Additional UI
    profile: 'Profilo',
    notifications: 'Notifiche',
    appearance: 'Aspetto',
    privacy: 'Privacy',
    logout: 'Esci',
    welcome: 'Benvenuto'
  }
};

// Simple translation function with basic interpolation support
export const t = (key: string, language: SupportedLanguage = 'en', params?: Record<string, string | number>): string => {
  const keys = key.split('.');
  let value: any = translations[language];

  for (const k of keys) {
    value = value?.[k];
  }

  let result = value || key; // Fallback to key if translation not found

  // Simple interpolation for {param} placeholders
  if (params && typeof result === 'string') {
    Object.entries(params).forEach(([paramKey, paramValue]) => {
      result = result.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramValue));
    });
  }

  return result;
};

// Simple currency formatting - following existing utility pattern
export const formatCurrency = (amount: number, currency: string = 'EUR'): string => {
  try {
    const locale = currency === 'EUR' ? 'it-IT' : 'en-US';
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency: currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }).format(amount);
  } catch (error) {
    // Fallback formatting
    const symbol = currency === 'EUR' ? '€' : '$';
    return `${symbol}${amount.toFixed(2)}`;
  }
};

// Get user's language from localStorage or browser (simple detection)
export const getUserLanguage = (): SupportedLanguage => {
  try {
    // Check localStorage first
    const saved = localStorage.getItem('subhub-language') as SupportedLanguage;
    if (saved && (saved === 'en' || saved === 'it')) {
      return saved;
    }
    
    // Simple browser detection - prioritize Italian
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('it') ? 'it' : 'en';
  } catch {
    return 'en'; // Safe fallback
  }
};

// Save user's language preference
export const setUserLanguage = (language: SupportedLanguage): void => {
  try {
    localStorage.setItem('subhub-language', language);
  } catch (error) {
    console.warn('Failed to save language preference:', error);
  }
};
